name: publish
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish to Github Container registry
        run:  | 
                 docker build . --tag ghcr.io/vaburenkov/hello-docker-gcr-demo:latest
                 docker run ghcr.io/vaburenkov/hello-docker-gcr-demo:latest
                 docker push ghcr.io/vaburenkov/hello-docker-gcr-demo:latest
